version: '3'

services:
  db:
    image: postgres:15.2-alpine
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "user#12345"
      POSTGRES_USER: "user"
      POSTGRES_DB: zawilian
    ports:
      - '5432:5432'
      
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - server
      # - dashboard
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  server:
    container_name: server
    build: 
      context: "./server/"
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - ./server/.env
    restart: unless-stopped

  # dashboard:
  #   container_name: dashboard
  #   build: 
  #     context: "./dashboard/"
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - server
  #   env_file:
  #     - ./.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    depends_on:
      - db


volumes:
  database: 
# version: '3'
# services:
#   db:
#     image: mongo:latest
#     volumes:
#       - db:/data/db
      
#   nginx:
#     image: nginx:stable-alpine
#     depends_on:
#       - ecommerce_api
#     restart: always
#     volumes:
#       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#     ports:
#       - "80:80"
#   ecommerce_api:
#     build: 
#       context: "./server/"
#       dockerfile: Dockerfile
#     depends_on:
#       - redis
#     env_file:
#       - ./.env
#     restart: unless-stopped
#     ports:
#       - "4000:4000"
  
#   ecommerce_client:
#     build: 
#       context: "./client/"
#       dockerfile: Dockerfile
#     depends_on:
#       - ecommerce_api
#     env_file:
#       - ./.env
#     ports:
#       - "3000:3000"
#     restart: unless-stopped

#   redis: 
#     image: redis:6.2.12-alpine
#     depends_on:
#       - db
# volumes:
#   db: 